version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm test

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.backend
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    command: npm test
